// flow-typed signature: eb497249a0b0985549d09937bc98a174
// flow-typed version: <<STUB>>/yargs_v^17.3.1/flow_v0.169.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'yargs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'yargs' {
  declare module.exports: any;
}

declare module 'yargs/helpers' {
  declare module.exports: any;
}
